logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: false
      maxPayloadLength: 10000
      urlPattern: "/home/*"
  baseUrl: "https://konradboniecki.com.pl"
server:
  ssl:
    enabled: false
    key-alias: budget-ssc
    key-store: budget-ssc.p12
    key-store-type: PKCS12
    key-store-password: '{cipher}7d48901eda44ffbd07f11fef74051cbd160c402c0662811ce2a35593ca7de110'
    trust-store: budget-ssc.p12
    trust-store-password: '{cipher}7d48901eda44ffbd07f11fef74051cbd160c402c0662811ce2a35593ca7de110'
spring:
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  profiles: default
  spring:
    thymeleaf:
      mode: HTML
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
    discoveryClientEnabled: false
health:
  config:
    enabled: false
    time-to-live: 3600000
---
spring:
  profiles: test
  profiles.include: default
