logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: true
      maxPayloadLength: 10000
spring:
  profiles: default
  jpa:
    open-in-view: false
    hibernate:
      dll-auto: update
      dialect.storage_engine: innodb
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: '{cipher}b3b3c8caeca88f16288f6ecf5f5079691e3419fd9eab3307ada090175df49213c57fc53e5c77a8f4a0ae231fae6b208f470b8bb5a0bbbc1c638d165269027d63336db5112cdf43723677322b0f777c3a9f286b025bb2a1fbdc6c8af0dd4b09d2aeba5b1e79e39a2a6b7c8ebf35c50c88'
    driver-class-name: com.mysql.jdbc.Driver
    username: '{cipher}38c657b97c6d07c4e54782c8d4dac576487aa0d5e85434bbb5a1a461de73e5bd'
    password: '{cipher}84d8c2ac20ed27bcc1628b488fdec939cc9063538e44b5f96a5dca972fa83fe7'
    continue-on-error: false
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
health:
  config:
    time-to-live: 3600000
---
spring:
  profiles: test
  profiles.include: default
