logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  http2:
    enabled: true
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  prometheus.metrics.export.enabled: true
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: false
      maxPayloadLength: 10000
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      database: budget-management
      uri: '{cipher}698d85f0b28a3ba9b8b6802cd44862ad9a674dc7abec812e50d903210a3dc2e27a310dec95b5697d970a9fc42d3ee6704e2afbad1f0fce59972dc664de639056e94210324a2228ca49d6e75f156f0aa81d4820077b1b80f749a900f39847af5f893717487ce0dd8417d115919e5a2b65'
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  security:
    user:
      name: '{cipher}99bcb43e165747f915eeffc7931ca55af9081f1314d5687bd5d994c99c76173c'
      password: '{cipher}38130b35a4ab1fb31c45494c8e07ecdabc66aa5b9549f9233bc29bd1bcd35bfa'
health:
  config:
    enabled: false
    time-to-live: 3600000
