logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: false
      maxPayloadLength: 10000
  baseUrl:
    gateway: "https://konradboniecki.com.pl"
    familyManagement: "http://family-management"
spring:
  profiles: default
  jpa:
    open-in-view: false
    hibernate:
      dll-auto: update
      dialect.storage_engine: innodb
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: '{cipher}312b9b09c6fa6d9afe40328a0e6bfd09a69fba04c55054810a7ca794154f50b45aeec06990ea63cf52e983fe08b44a07ba4f3bb9904906f1fa25becb75d7c8520a5a87e0d847c43232faa3bde8282e4b9cc77b48bdb19db2597473f5ddd3cbb537d508b84eaf015fdc4df3caac9573fb'
    driver-class-name: com.mysql.jdbc.Driver
    username: '{cipher}38c657b97c6d07c4e54782c8d4dac576487aa0d5e85434bbb5a1a461de73e5bd'
    password: '{cipher}84d8c2ac20ed27bcc1628b488fdec939cc9063538e44b5f96a5dca972fa83fe7'
    continue-on-error: false
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  security:
    user:
      name: '{cipher}99bcb43e165747f915eeffc7931ca55af9081f1314d5687bd5d994c99c76173c'
      password: '{cipher}38130b35a4ab1fb31c45494c8e07ecdabc66aa5b9549f9233bc29bd1bcd35bfa'
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
    discoveryClientEnabled: false
    sender:
      type: web
health:
  config:
    enabled: false
    time-to-live: 3600000
---
spring:
  profiles: test
  profiles.include: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
---
spring:
  profiles: operations
  profiles.include: default
