logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  http2:
    enabled: true
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  prometheus.metrics.export.enabled: true
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: false
      maxPayloadLength: 10000
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      database: family-management
      uri: '{cipher}ecafa50f28bd559e855fdb87af470e3c7193ea7649006efaa8200f337d9933c8623a4b6a2cdfda7e4c371f02e974913f82ed1cf9fbca31063dc16b9b04ac462b45017731382465f2e306f0c6923a0cbc40d8359f199b807948b84e4f4d822e68ec635ae81a1e904be101b7d733e34888'
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  security:
    user:
      name: '{cipher}99bcb43e165747f915eeffc7931ca55af9081f1314d5687bd5d994c99c76173c'
      password: '{cipher}38130b35a4ab1fb31c45494c8e07ecdabc66aa5b9549f9233bc29bd1bcd35bfa'
health:
  config:
    enabled: false
    time-to-live: 3600000
