server:
  port: 8080
spring:
  profiles: default
  thymeleaf:
    mode: HTML
  jpa:
    hibernate:
      dll-auto: update
      dialect.storage_engine: innodb
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: test
  profiles.include: default
  cloud:
    config:
      enabled: false
