server:
  port: 8081
spring:
  thymeleaf:
    mode: HTML
  jpa:
    hibernate:
      dll-auto: update
      dialect.storage_engine: innodb
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
