server:
  port: 8080
spring:
  application:
    name: some_name
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8080
  thymeleaf:
    mode: HTML
  jpa:
    hibernate:
      dll-auto: update
      dialect.storage_engine: innodb
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
