logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    mappings.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true
budget:
  chassis:
    http-logging:
      enabled: true
      includeQueryString: true
      includePayload: true
      includeHeaders: false
      maxPayloadLength: 10000
  baseUrl:
    gateway: "https://konradboniecki.com.pl"
  mail:
    replyTo: '{cipher}5cdd1f83a626ae32423d66139c6b3d3511fba068dde0c724c38d982133cf71890519b7d3ddb4064dde843bbfc4c2e2d3'
spring:
  thymeleaf.mode: HTML
  mail:
    host: smtp.gmail.com
    port: 587
    username: '{cipher}9923989b199b06180762c10cd60e715f105dd57e5261402d585f3a1da751d4d2b25cf1000044ae9da9d5fa86b97da05f'
    password: '{cipher}24f5443b86730a3a827a6bb8a2836277db293a9f72daf44f42eeef89eb77758168398308bc2725d82dcbfc7b3d35498a'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  security:
    user:
      name: '{cipher}99bcb43e165747f915eeffc7931ca55af9081f1314d5687bd5d994c99c76173c'
      password: '{cipher}38130b35a4ab1fb31c45494c8e07ecdabc66aa5b9549f9233bc29bd1bcd35bfa'
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
    discoveryClientEnabled: false
health:
  config:
    enabled: false
    time-to-live: 3600000
---
spring:
  profiles: test
  profiles.include: default
  test.mockmvc.print: none
